spring:
  datasource:
    masterdb:
      jdbc-url: jdbc:postgresql://${POSTGRES_MASTER_DB}/nsadb
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
    slave-1-db:
      jdbc-url: jdbc:postgresql://${POSTGRES_SLAVE_DB}/nsadb
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  mail:
    host: ${SMTP_HOST}
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    address: ${SMTP_ADDRESS}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

rate-limit:
  max-requests-per-minute: 30

jwt:
  expiration: 24
  auth-header: App-Auth
  secret: ${JWT_SECRET}

